# Generated by Django 6.0 on 2026-01-07 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the skill (e.g., 'Python', 'JavaScript', 'Project Management')", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The resume file (PDF, DOCX, etc.)', upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True, help_text='Text content extracted from the resume file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the resume was uploaded')),
                ('user', models.ForeignKey(help_text='The user who uploaded this resume', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job role title (e.g., 'Python Developer', 'Data Scientist')", max_length=100)),
                ('required_skills', models.ManyToManyField(help_text='Skills required for this job role', related_name='job_roles', to='core.skill')),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_skills', models.TextField(help_text='Skills from the resume that match the job role requirements')),
                ('missing_skills', models.TextField(help_text='Required skills that are missing from the resume')),
                ('match_percentage', models.FloatField(help_text='Percentage of required skills found in the resume (0-100)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the analysis was performed')),
                ('job_role', models.ForeignKey(help_text='The job role being compared against', on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_results', to='core.jobrole')),
                ('resume', models.ForeignKey(help_text='The resume being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_results', to='core.resume')),
            ],
            options={
                'verbose_name': 'Skill Gap Result',
                'verbose_name_plural': 'Skill Gap Results',
                'ordering': ['-analyzed_at'],
                'unique_together': {('resume', 'job_role')},
            },
        ),
    ]
