"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k4%c$_n&608j8q@p=q$fb!^oc=j_ie+gfe%5huoqu_c=u7w#6b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Google OAuth2 Client ID
# Users need to replace this with their actual Client ID from Google Cloud Console
GOOGLE_OAUTH2_CLIENT_ID = '800542912132-5hrt7i7rnsd0hr3ed7v7ea02fobrph5c.apps.googleusercontent.com'

# Application definition
# INSTALLED_APPS lists all Django applications that are enabled in this project
# 'rest_framework' - Django REST Framework: Provides tools for building REST APIs
#                    (serializers, viewsets, APIView, etc.)
# 'core' - Our custom app for the AI-Assisted Resume Analyzer project

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'corsheaders',  # CORS headers for allowing frontend-backend communication
    'rest_framework',  # Django REST Framework for building APIs
    'rest_framework.authtoken',  # Token authentication for DRF
    # Local apps
    'core',  # Our main application for resume analyzer features
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be near the top)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 
# PostgreSQL Configuration:
# For production, use PostgreSQL. Update the credentials below with your actual database details.
# For initial development/testing, SQLite is fine (currently active below).
#
# To use PostgreSQL:
# 1. Install PostgreSQL on your system
# 2. Create a database: CREATE DATABASE resume_analyzer;
# 3. Update the credentials below (NAME, USER, PASSWORD, HOST, PORT)
# 4. Uncomment the PostgreSQL configuration and comment out SQLite

DATABASES = {
    # SQLite configuration (for initial development - works out of the box)
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    
    # PostgreSQL configuration (for production - uncomment and update credentials)
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'resume_analyzer',  # Database name - update this
    #     'USER': 'your_username',    # PostgreSQL username - update this
    #     'PASSWORD': 'your_password',  # PostgreSQL password - update this
    #     'HOST': 'localhost',        # Database host (usually 'localhost')
    #     'PORT': '5432',             # PostgreSQL default port
    # }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# CORS (Cross-Origin Resource Sharing) Configuration
# https://github.com/adamchainz/django-cors-headers
#
# Why CORS is needed:
# - Frontend runs on http://localhost:5173 (Vite dev server)
# - Backend runs on http://127.0.0.1:8000 (Django server)
# - Browsers block requests between different origins (different ports = different origins)
# - CORS headers tell the browser it's safe to allow these cross-origin requests
#
# CORS_ALLOWED_ORIGINS: List of frontend URLs that can access the backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite default dev server port
    "http://127.0.0.1:5173",   # Alternative localhost format
]

# Allow credentials (cookies, authorization headers) to be sent with requests
CORS_ALLOW_CREDENTIALS = True

# Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
CORS_ALLOW_ALL_ORIGINS = False  # Set to False for security (only allow specific origins above)

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Django REST Framework configuration
# TokenAuthentication is available for all endpoints, but views must
# explicitly set permission_classes to enforce authentication.
# By default, AllowAny lets any request through; specific views can override.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}
